name: abybaby_assignment
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.5.4
  dio: ^5.9.1
  get_it: ^9.2.0
  flutter_bloc: ^9.1.1
  reactive_forms: ^18.2.2
  freezed_annotation: ^3.1.0
  json_annotation: ^4.10.0
  equatable: ^2.0.8
  

dev_dependencies:
  json_serializable: ^6.12.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  freezed: ^3.2.5
  build_runner: ^2.10.5

flutter:
  uses-material-design: true
